project_id = "kvofxprsmzyxssjpyfmy"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[auth]
enabled = true
site_url = "https://obrio-ai.obrioai.workers.dev"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "https://obrio-ai.obrioai.workers.dev/**",
  "https://*.workers.dev/**"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[storage]
enabled = true

[vector]
enabled = false
